### ISSUE TITLE
Test Webhooks Extension with Triggers 0.3

### ISSUE THREAD

**Issue by ncskier** [tektoncd/experimental#480] opened 2020-02-26 21:02 UTC
# Expected Behavior
The Triggers v0.3.0 release went live yesterday (https://github.com/tektoncd/triggers/releases/tag/v0.3.0), so let's see what features continue to work and if any need to be added.

# Steps to reproduce the problem

## Scenario 1: fresh install
1. Install Triggers v0.3.0
1. Install master of the Tekton Dashboard & Webhooks Extension

## Scenario 2: upgrade
1. Install Triggers v0.2.1
1. Install master of the Tekton Dashboard & Webhooks Extension
1. Create a functioning webhook
1. Install Triggers v0.3.0
1. Try to use the existing webhook

# Environment
- Kubernetes Platform:
Any

- Tekton Pipelines version:
master

- Tekton Triggers version:
v0.3.0

- Tekton Dashboard version:
master

- Webhooks Extension version:
master

**Comment by ncskier** [comment] 2020-02-26 21:14
### Scenario 1: fresh install

I've done some testing with Triggers v0.3.0 on OpenShift, and I was able to create a functioning webhook using the [pipeline hotel buildah resources](https://github.com/pipeline-hotel/example-pipelines/tree/master/triggers-resources/config/github/buildah). On GitHub Enterprise, I was able to trigger a PipelineRun from a push event, and I was able to create a PullRequest with the monitor Task providing automated test results in the PullRequest.

### Scenario 2: upgrade

Unfortunately, there seems to be an error with upgrading directly from Triggers v0.2.1 to v0.3.0. The existing EventListener was unable to fill its parameters according to the specified TriggerBinding.

After deleting my existing webhook and recreating it, I was able to use the Webhooks Extension as expected.

I'm not exactly sure what's going wrong in this upgrade scenario; there's still some more work to be done. Also, I don't know if all the webhooks need to be deleted (deleting the EventListener) for the fix to take effect.

**Comment by ncskier** [comment] 2020-02-28 15:24
There was a bug causing the upgrade issue (fixed with this PR: https://github.com/tektoncd/triggers/pull/461). I've tested the Webhooks Extension with PR 461, and it solves the upgrade problem 👍

**Comment by a-roberts** [comment] 2020-03-10 10:01
Had a good go today with 12 webhooks at once on GHE, no changing behaviour observed (so, no backend scalability issues (though our UI does take a while to render the webhooks, presumably as we're iterating through the EventListener). No funky logs spotted in our EL, apart from this.


```
2020/03/10 09:46:37 [adam8-tekton-pipelines-push-event] Clone URL coming in as JSON: https://github.ibm.com/AROBERTS/devops-world-example.git
2020/03/10 09:46:37 [adam8-tekton-pipelines-push-event] Handling GitHub Event with delivery ID: f55d8cc8-62b3-11ea-812f-2f7fcbbf16a0
2020/03/10 09:46:37 [adam8-tekton-pipelines-push-event] Validation PASS (repository URL, secret payload, event type checked)
2020/03/10 09:46:37 http: panic serving 10.1.5.74:45852: runtime error: invalid memory address or nil pointer dereference
goroutine 1455 [running]:
net/http.(*conn).serve.func1(0xc0005c0aa0)
	net/http/server.go:1767 +0x139
panic(0x1034960, 0x1bba870)
	runtime/panic.go:679 +0x1b2
main.addBranchAndTag(0x113cf20, 0xc0005c00a0, 0x113cf20, 0xc0005c00a0, 0xe, 0x0, 0x0)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/utils.go:119 +0x7aa
main.handlePush(0xc00076e400, 0x12faa00, 0xc0003d60e0, 0xc000042c90, 0x21, 0xc000020000, 0x1caf, 0x1e00, 0x0, 0xc0006e5340, ...)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:69 +0x387
main.HandleGitHub(0xc00076e400, 0x12faa00, 0xc0003d60e0, 0xc000042c90, 0x21, 0xc00066cdc0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:38 +0x2b7
main.main.func1(0x12faa00, 0xc0003d60e0, 0xc00076e400)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/interceptor.go:86 +0xcce
net/http.HandlerFunc.ServeHTTP(0x11f58a8, 0x12faa00, 0xc0003d60e0, 0xc00076e400)
	net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x1bcd940, 0x12faa00, 0xc0003d60e0, 0xc00076e400)
	net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0002681c0, 0x12faa00, 0xc0003d60e0, 0xc00076e400)
	net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0005c0aa0, 0x12ff080, 0xc000a18580)
	net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	net/http/server.go:2928 +0x384
2020/03/10 09:46:37 [adam2-tekton-pipelines-push-event] Clone URL coming in as JSON: https://github.ibm.com/AROBERTS/devops-world-example.git
2020/03/10 09:46:37 [adam2-tekton-pipelines-push-event] Handling GitHub Event with delivery ID: f55d8cc8-62b3-11ea-812f-2f7fcbbf16a0
2020/03/10 09:46:37 [adam2-tekton-pipelines-push-event] Validation PASS (repository URL, secret payload, event type checked)
2020/03/10 09:46:37 http: panic serving 10.1.5.74:45870: runtime error: invalid memory address or nil pointer dereference
goroutine 1464 [running]:
net/http.(*conn).serve.func1(0xc0005c1040)
	net/http/server.go:1767 +0x139
panic(0x1034960, 0x1bba870)
	runtime/panic.go:679 +0x1b2
main.addBranchAndTag(0x113cf20, 0xc00002c280, 0x113cf20, 0xc00002c280, 0xe, 0x0, 0x0)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/utils.go:119 +0x7aa
main.handlePush(0xc00001a900, 0x12faa00, 0xc0000b0460, 0xc0009157a0, 0x21, 0xc0001f2000, 0x1caf, 0x1e00, 0x0, 0xc000749100, ...)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:69 +0x387
main.HandleGitHub(0xc00001a900, 0x12faa00, 0xc0000b0460, 0xc0009157a0, 0x21, 0xc0003fb2c0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/github.go:38 +0x2b7
main.main.func1(0x12faa00, 0xc0000b0460, 0xc00001a900)
	github.com/tektoncd/experimental/webhooks-extension/cmd/interceptor/interceptor.go:86 +0xcce
```

👀

**Comment by a-roberts** [comment] 2020-03-10 16:02
Also https://github.com/tektoncd/experimental/issues/488

**Comment by a-roberts** [comment] 2020-03-12 16:42
No problems with this now to report, can't reproduce the Go panic and happy to open new issues should anything pop up, closing

**Closed by a-roberts** 2020-03-12 16:42 UTC
