### ISSUE TITLE
Webhook deleted incorrectly (with the same name)

### ISSUE THREAD

**Issue by dibbles** [tektoncd/experimental#495] opened 2020-03-23 17:27 UTC
# Expected Behavior

If I delete one webhook, others should not be deleted.

# Actual Behavior

It is possible to create two webhooks with same name, on different repos, in the same namespace, running the same pipeline.  Deleting one of these webhooks appears to cause the deletion of the other (and I have also noticed a left over monitor in the eventlistener).

Either the creation restrictions are wrong and do not match those of previous versions OR the deletion code is not functioning correctly.

# Steps to Reproduce the Problem

1. create webhook called X on repo Y running pipeline A in namespace B
2. create webhook called X on repo Z running pipeline A in namespace B
3. delete the second of these webhooks

# Additional Info

**Comment by a-roberts** [comment] 2020-04-03 09:48
@CarolynMabbott's out at the moment so I've unassigned and moved it to the top of the backlog

**Comment by a-roberts** [comment] 2020-04-06 08:08
If nobody else picks this up I will after testing the basics with Triggers 0.4, sounds terrible

**Comment by a-roberts** [comment] 2020-04-07 11:10
I reproduced a problem here, I created two and deleted the first with the UI which resulted in both webhooks being deleted actually. Deleting the last one actually worked ok for me but there's certainly something odd here going on anyway so will have a look.

**Comment by a-roberts** [comment] 2020-04-07 13:19
I'm restricting the webhook names to be unique, saves us writing plenty of complex code and I think it makes sense for them to be anyway to reduce confusion (be it in the logs or through the UI), have documented it as a limitation. There are breaking changes in this release anyway due to using Pipelines 0.11 (the example pipelines in the hotel can be used as a reference once my PRs are in).

Will carry out further testing then remove WIP from both my PRs and away we go.

**Comment by a-roberts** [comment] 2020-04-08 14:33
Merged so closing

**Closed by a-roberts** 2020-04-08 14:33 UTC
Labels: kind/bug, priority/critical-urgent, triggers, webhooks
